### ISSUE TITLE
add package to conda-forge

### ISSUE THREAD

**Issue by systemshift** [data61/python-paillier#81]
Been trying to build a conda package that depends on phe, while it works fine with pip, the conda CI uses conda to install python dependencies.

I have searched the conda repos and it appears the project only exists on pypi https://anaconda.org/search?q=phe.

using `conda skeleton pypi phe` would generate the required yaml file, but a maintainer is required to add his username at the end of the file.

**Comment by wilko77** [comment]
Hi, thanks for pointing that out. I created a PR to add phe to conda-forge [here](https://github.com/conda-forge/staged-recipes/pull/11576)

**Comment by systemshift** [comment]
Thank you. I have been taking a look on the PR every few days since I can only wait for it to be merged. Once it does please mention this in the issue or close the issue so I get email notification.
