### ISSUE TITLE
How to implement   D(E(a)**b) =a * b use code ?

### ISSUE THREAD

**Issue by DiveCoders** [data61/python-paillier#83]
Dear friends:

In alternative_base.py ，I konw how to  implement the property：**D(E(a) * E(b)) = a + b**。

And then how to use code to  implement   D(E(a)**b) =a * b？

**For example：
a=-2.1  b=2.3  
how to use code to verify D（E ( -2.1 ) ** 2.3) ==-2.1 * 2.3**

I am a novice, I hope to get your answer, thank you very much！

**Comment by gusmith** [comment]
Quite late, but may still be of help.
A simple code example for this:
```
import phe as paillier

public_key, private_key = paillier.generate_paillier_keypair()
a = -2.1
b = 2.3
# Encrypted value of a
a_enc = public_key.encrypt(a)
# Encrypted value of a * b
mult_enc = a_enc * b
# Decrypt
mult_decr = private_key.decrypt(mult_enc)
assert a * b == mult_decr
```

You can also find such operations examples in https://python-paillier.readthedocs.io/en/1.4.0/usage.html#role-2 .
Hoping this help.
