### ISSUE TITLE
how to change the type of the data that after encrypting?

### ISSUE THREAD

**Issue by wlnancy** [data61/python-paillier#84]
when using it to encrypt tensor, how to change the type of the data after encrypting cannot into other type like float or tensor?Because I want to save the encrypted data using list or or numpy but it failed. And the error is that the type can't be 'EncryptedNumber'.

**Comment by hardbyte** [comment]
There isn't really enough information in your issue to understand what is going on. Please reopen with a minimal example if this is still an issue.
