### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by wlnancy** [data61/python-paillier#85]
when I run the code in python37,it occurs the error that NameError: name 'long' is not defined in file phe-1.3.0-py3.7.egg\phe\paillier.py line 173,in encrypt, line 188, in encrypt_encoded,line 120 in raw_encrypt

**Comment by wilko77** [comment]
Something seems odd about this error. I cannot find any reference to 'long' in the paillier.py file.
You can try using the latest release 1.4.0?
Also, can you provide an example, such that I can reproduce the error?

**Comment by wlnancy** [comment]
Thanks，I have solved the problem by using the lastest version1.4.0.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "data61/python-paillier"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 上午6:33
收件人:&nbsp;"data61/python-paillier"<python-paillier@noreply.github.com&gt;;
抄送:&nbsp;"王蕾"<945389942@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [data61/python-paillier] run error (#85)





 
Something seems odd about this error. I cannot find any reference to 'long' in the paillier.py file.
 You can try using the latest release 1.4.0?
 Also, can you provide an example, such that I can reproduce the error?
