### ISSUE TITLE
How can I encrypt my dataset (some data about electricity) with Paillier?

### ISSUE THREAD

**Issue by Lsw-98** [data61/python-paillier#88]
How can I encrypt my dataset (some data about electricity) with Paillier?

**Comment by YannisDuhamelle** [comment]
First you need to generate a public/private key pair, then you need to use your public key to encrypt (the private key will be used for decryption)
You should look at those use cases example (I think the first use case is close to what you need):
https://python-paillier.readthedocs.io/en/stable/usage.html

**Comment by Lsw-98** [comment]
Why did I install the pycrypto module and make an error while executing the Import command
![捕获](https://user-images.githubusercontent.com/70066311/107121637-83e05180-68ce-11eb-9dea-5e2466240053.PNG)

**Comment by YannisDuhamelle** [comment]
I do not know about this error, but for this Paillier encryption you need only to use the phe module:
`pip install phe`

**Comment by Lsw-98** [comment]
All right, thank you!
