### ISSUE TITLE
TypeError: Don't know the precision of type <class 'str'>

### ISSUE THREAD

**Issue by Lsw-98** [data61/python-paillier#89]
Hello, I have the following error when encrypting string data. Does Phe not support string data encryption? Or has been supported, but my method is wrong, if my method is wrong, can you ask how to encrypt string data? (the PHE version I use is 1.4)，If I only encrypt the kWh (power consumption) of the third column, I can encrypt and calculate it. But when I want to encrypt the date (time) of the second column at the same time, he made the following error:
![Error information](https://user-images.githubusercontent.com/70066311/109380946-6e30db80-7912-11eb-8736-a788cc22d8e0.PNG)

What does the precision of type mean？
![Data to be encrypted](https://user-images.githubusercontent.com/70066311/109380977-8c96d700-7912-11eb-8823-266f463940c3.PNG)

**Comment by gusmith** [comment]
Python Paillier is made to handle numbers only. While you could transform a string into a list of numbers (e.g. list of char values), you should ask yourself the reason you would like to do it with Paillier encryption on these strings. Using an homomorphic encryption, you would usually use the encrypted values to run arithmetic operations on them. In the case of a string, what would you expect as an addition of strings?
If you just want to encrypt and decrypt the string values without running operations on their encrypted forms, I would recommend more standard encryption algorithms (non homomorphic).
If you still want to use Paillier encryption on the dates fields, you will first have to transform them into numbers.

**Comment by hardbyte** [comment]
Encrypted power usage... sounds like a pretty cool application! As @gusmith said, you need to convert your `str` KW values into numbers (either float or int is fine).
