### ISSUE TITLE
Encrypted data change 

### ISSUE THREAD

**Issue by yunusvrgl** [data61/python-paillier#90]
In my project, When I encrypt an integer the output is like <phe.paillier.EncryptedNumber object at 0x7f6074f0f5e0> this format but I just need a part which is "0x7f6074f0f5e0". How can I accomplish this? If you can help I would be very appreciated

**Comment by hardbyte** [comment]
The string representation is something like `<phe.paillier.EncryptedNumber object at 0x7f6074f0f5e0>`, I wouldn't consider that the output though. 

Are you **sure** you need the address of the Python object and not the `encrypted_number.ciphertext()`?

**Comment by yunusvrgl** [comment]
I encoded and encrypted the values as in the example "alternative_base.py". Aren't those values counted as ciphertexts?

**Comment by hardbyte** [comment]
No the value `0x7f6074f0f5e0` in the string representation `<phe.paillier.EncryptedNumber object at 0x7f6074f0f5e0>` isn't the ciphertext, it is the address of the object in memory.

You almost certainly want to call `your_encrypted_value_instance.ciphertext()` and you may need the exponent as well - stored as  `your_encrypted_value_instance.exponent`.
