### ISSUE TITLE
Store encrypted numbers and keys to external files

### ISSUE THREAD

**Issue by lovingmage** [data61/python-paillier#91]
Hi,
Once I encrypt a number, how do I store the encrypted number in an external file, and also how do I save the private key and public key to an external file? Many thanks if you could provide any suggestions.

**Comment by hardbyte** [comment]
Suggest reading [the documentation on serializing both encrypted numbers and keys](https://python-paillier.readthedocs.io/en/develop/serialisation.html)

**Comment by lovingmage** [comment]
That's really helpful, thanks a lot.
