### ISSUE TITLE
Ciphertext Scalar Multiplication

### ISSUE THREAD

**Issue by yunusvrgl** [data61/python-paillier#92]
I couldn't multiply EncryptedNumber.ciphertext ()  with a random scalar value. What should I do about this situation?

**Comment by hardbyte** [comment]
You want to multiply the `EncryptedNumber` directly with the scalar value. The `ciphertext` is the lower level (internal) data.

**Comment by yunusvrgl** [comment]
My data is in ciphertext format instead of EncryptedNumber so that I need to use scalars and ciphertexts. Do I have any chance for making this multiplication operation? I'm searching for this method for a long time but I couldn't figure it out.

**Comment by hardbyte** [comment]
Can you post an example? 

If you have raw encrypted data (just the ciphertext) you can still create an `EncryptedNumber` before multiplication

**Comment by yunusvrgl** [comment]
For example, I need to encrypt some values write their ciphertext to a file. Then I have to read those ciphertexts from it and multiply it with a random non-zero scalar value.

**Comment by hardbyte** [comment]
Great, that is possible with this library if you follow the documentation on [serialization](https://python-paillier.readthedocs.io/en/develop/serialisation.html) and [usage](https://python-paillier.readthedocs.io/en/develop/usage.html#role-2).

If you take on board my suggestion and are still having trouble please post a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
