### ISSUE TITLE
a = 5, b=5, why enc(a) == enc(b) returns false？

### ISSUE THREAD

**Issue by napoay** [data61/python-paillier#96]
```
from phe import paillier
a = 5
b = 5

encA =  public_key.encrypt(5)
encB =  public_key.encrypt(5)

print(encA==encB) #False
```

If A and B are equal, are their corresponding ciphertexts equal?

**Comment by manglemix** [comment]
no, as a random obfuscator is included in the encryption such that encryptions of the same plaintext are different numbers. This is to prevent an attacker from learning the plaintext based on patterns of similarities

**Comment by napoay** [comment]
Does paillier support homomorphic equality function? In other words, how to judge that two ciphertexts are equal?

**Comment by manglemix** [comment]
There are non interactive zero knowledge proofs that the encrypt or can generate to prove that two ciphertext are equal. But this is not currently supported in this package. You have to find a paper that describes one of these methods and implement this yourself
