### ISSUE TITLE
how to set key length?

### ISSUE THREAD

**Issue by napoay** [data61/python-paillier#97]
The key length will directly affect the operation speed. 

How to choose the key length? 

Is there a minimum key length under the premise of ensuring security?

**Comment by hardbyte** [comment]
Have a look at [this benchmark](https://github.com/data61/python-paillier/blob/master/examples/benchmarks.py#L38-L71) to see how to set the key length - also you might be interested in running that benchmark as it tries various operations with different key sizes.

We based the [default key length](https://github.com/data61/python-paillier/blob/master/phe/paillier.py#L31-L34) on published research and recommendations - have a look at https://www.keylength.com

**Comment by napoay** [comment]
Thanks a lot. @hardbyte
